// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZqcDNq_VXzTG9QFG6k_wnOB-9MQwOSJA',
    appId: '1:371466923603:web:d93fc48d28bf9d5e9820a6',
    messagingSenderId: '371466923603',
    projectId: 'bootstrap-65360',
    authDomain: 'bootstrap-65360.firebaseapp.com',
    storageBucket: 'bootstrap-65360.firebasestorage.app',
    measurementId: 'G-1K947WVD2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHdGi-1BqYmeJDXvCcLpBZHEX0TjYjzWA',
    appId: '1:371466923603:android:32bb472113665b889820a6',
    messagingSenderId: '371466923603',
    projectId: 'bootstrap-65360',
    storageBucket: 'bootstrap-65360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGZ6lbaa3tX1Ej0MND5lCJ4N8eiXyaUSQ',
    appId: '1:371466923603:ios:69bfc89af671c91d9820a6',
    messagingSenderId: '371466923603',
    projectId: 'bootstrap-65360',
    storageBucket: 'bootstrap-65360.firebasestorage.app',
    iosBundleId: 'com.example.bootstrap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGZ6lbaa3tX1Ej0MND5lCJ4N8eiXyaUSQ',
    appId: '1:371466923603:ios:69bfc89af671c91d9820a6',
    messagingSenderId: '371466923603',
    projectId: 'bootstrap-65360',
    storageBucket: 'bootstrap-65360.firebasestorage.app',
    iosBundleId: 'com.example.bootstrap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZqcDNq_VXzTG9QFG6k_wnOB-9MQwOSJA',
    appId: '1:371466923603:web:9e21735127cf094f9820a6',
    messagingSenderId: '371466923603',
    projectId: 'bootstrap-65360',
    authDomain: 'bootstrap-65360.firebaseapp.com',
    storageBucket: 'bootstrap-65360.firebasestorage.app',
    measurementId: 'G-NRGPMMD9EX',
  );
}
